### ISSUE TITLE
Package Not working!

### ISSUE THREAD

**Issue by mahamedmahad** [jamaaldev/birthday#1]
@jamaaldev 

package is not working!!

include ```
mode.exports = DaysToCome```   in your root index.js file instead  ```export {DaysToCome}```

another issue is this one 

(node:24528) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by jamaaldev** [comment]
please check readme and follow step by step if this issue still there please send me your file or show me how you using it.

**Comment by mahamedmahad** [comment]
the problem is from index file. 

![Screenshot 2021-11-29 044629](https://user-images.githubusercontent.com/55987068/143805645-387c6471-906c-43af-a0d2-c15a136d319e.png)

**Comment by jamaaldev** [comment]
can you show me the html file and the script how you imported did you followed my steps in readme ? example in html <script type="module" src="script.js"></script>
and 
import {DaysToCome} from '/node_modules/birthday-check/index.js'
did you really read the readme ?

**Comment by mahamedmahad** [comment]
![Screenshot 2021-11-29 124138](https://user-images.githubusercontent.com/55987068/143861954-7cd517ac-5c27-43ea-9221-0fb7f630a222.png)

main.js  code 
```js

import {DayToCome} from 'birthday-check';



const user = {
    textGreeting:'Happy BirthDay',
    textDaysLeft:'',
    textDayLeft:'',
    textBirthDay:'21'
}
let birthday = new DayToCome(user);

console.log(birthday)
```

console output: 
main.js:1 ``` Uncaught SyntaxError: Cannot use import statement outside a module```

**Comment by jamaaldev** [comment]
add the type="module" in your script example you forget to add 
```
<script type="module" src="main.js"></script>
```
please check readme https://github.com/jamaaldev/birthday#readme

import like this:<br> ``` import {DaysToCome} from '/node_modules/birthday-check/index.js' ```
not like this: ``` import {DayToCome} from 'birthday-check'; ```

please let me know if this solved and always read the readme file. thank you so much for reporting issue.

**Comment by mahamedmahad** [comment]
my bad, I just didn't read see that part  ```  type="module" ```


I think you can fix this issue so the users don't have to write ```type="module" ``` inside  their script files every time they import it inside html files. also shorten the pkg node_mode path to
 ```js 
 import {DayToCome} from 'birthday-check'; 
```
all this can be fixed  inside index.js by replacing this
```js
export {DaysToCome}
```
to 
```js
module.exports = DaysToCome
```


other than that, the Pkg works now!

**Comment by jamaaldev** [comment]
thank you so much i will take your advice can you check this website https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

you will know why i am using export i am gone test it to your solution if that works i will update the file, and also I am working now how to implement  in react because this only work with JavaScript vanilla

**Comment by jamaaldev** [comment]
thank you for the link is usefully information just to remind you NodeJS is for backend and i didn't created this package for that, I wanted to use in frontend if you read the readme you will know i said frontend, i will close this issue for now if you wish to reopen you are welcome thank you a lot @mahamedmahad
